# Generated by Django 5.0.4 on 2024-05-04 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Investimento', models.TextField(max_length=255)),
                ('valor', models.FloatField()),
                ('Pago', models.BooleanField(default=False)),
                ('Data', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
