# Generated by Django 5.0.4 on 2024-05-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invista_me', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='investimento',
            new_name='Investimentos',
        ),
    ]
